=== daanidev21/trabajoRemoto/test.dtd
<!ELEMENT arbol (especie+)>
<!ELEMENT especie (nombre, variedad, origen, color, maduracion, riego, precio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT variedad (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT maduracion (#PCDATA)>
<!ELEMENT riego (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ENTITY valor SYSTEM "valor de la entidad">

=== daanidev21/trabajoRemoto/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arbol SYSTEM "/Users/danizanon/Documents/Lenguajes de marcas/XML/EJ1/test.dtd">

<arbol>
    <especie>
        <nombre>Litchi</nombre>
        <variedad>Kway May Pink</variedad>
        <origen>Filipinas &valor; </origen>
        <color>rojo</color>
        <maduracion>agosto</maduracion>
        <riego>diario</riego>
        <precio>3.5</precio>
    </especie>
    <especie>
        <nombre>Mango</nombre>
        <variedad>Alphonso</variedad>
        <origen>India</origen>
        <color>amarillo</color>
        <maduracion>abril</maduracion>
        <riego>regular</riego>
        <precio>4.2</precio>
    </especie>
</arbol>
<planta>
    <especie>
        <nombre>Planta1</nombre>
    </especie>
</planta>
